### ISSUE TITLE
Feature Request: Add Teleporter hook/button to Train Tool

### ISSUE THREAD

**Issue by jasinkare** [imaginary-png/HuntHelper#10]
QoL addition, would like to be able to port to nearest aetheryte to flag, similar to how Maplinker has. Makes conducting much easier.

Outside of that, so far I'm in love with the plugin. Worked great for Stormblood train, unfortunate instances are broken but elsewise this will probably replace both Sonar and Maplinker for me.

If there's somewhere better to post things like this, please let me know!

**Comment by imaginary-png** [comment]
Can you lay out how you would like it to work? Like when you click on a hunt in the train window, it pops up a "Teleport to ****" dialogue?  

I've not used maplinker, so I'll check it out when I have time.

This seems like a useful addition, if I can make it work, but I can't promise any additional functionality anytime soon since I'll be busy with raiding and 6.2 content.

**Comment by jasinkare** [comment]
For maplinker specifically, there's just a "teleport" button, you click and it initiates the teleport via the Teleporter plugin, no other clicks needed. Attached a photo below, including a HH flag captured by maplink

No rush to add, of course, and it would also make Teleporter a dependency unless there was another way to do it, but it would consolidate tools into the train tool and make life super easy.

![image](https://user-images.githubusercontent.com/89516922/186824280-d74b50ec-637f-411d-ba73-6acd719cfa1a.png)

**Comment by imaginary-png** [comment]
Hey, I've managed to get this done today. Just needs to be approved by the Dalamud team.

Some caveats, but a good base feature that I might clean up in the future.

You can enable:  

- Teleport on name click (this is a bit meh since it will initiate tele if you're trying to reorder the list or something, don't recommend)
- Teleport on command use (/hhn)
- Teleport buttons 

Some caveats: 
- It will not teleport if the map has no aetheryte, such as the Dravanian Hinterlands, but doesn't really apply Endwalker hunts.
- It does not take into account shortcuts teleports that aren't Aetherytes on the same hunt map, such as going through Limsa > Zephyr gate for Lower La Noscea

but you know, these only really apply to older content that wouldn't be used in a hunt train. So I have no plans improving those parts.

![image](https://user-images.githubusercontent.com/70348218/187068599-e7bf2417-4277-4dd3-b34e-a004c8f49253.png)

**Comment by imaginary-png** [comment]
If you run into any issues or have any other ideas, please tell me! 

Thank you!
