### ISSUE TITLE
[Feature Request] Output the 1st person to hit an S rank into chat

### ISSUE THREAD

**Issue by ZohiDev** [imaginary-png/HuntHelper#28]
Would it be possible to write the name of the 1st person to hit/pull an S rank into the chat?

**Comment by imaginary-png** [comment]
Unfortunately this can't be done. 

Since we're limited by the data we receive from the server, there's no way to guarantee the info on the first person to hit. Only the first person who hit it and who's data is loaded on our client.

Notice when there's a lot of people, you'll see characters disappear and reappear?
